# Generated by Django 5.2.12 on 2026-03-20 10:20

import autoslug.fields
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("is_predefined", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Specialisation",
                "verbose_name_plural": "Specialisations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "username",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="_get_username_base", unique=True
                    ),
                ),
                ("profile_photo_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Profile",
                "verbose_name_plural": "Client Profiles",
            },
        ),
        migrations.CreateModel(
            name="GymProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gym_name", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="gym_name", unique=True
                    ),
                ),
                ("admin_full_name", models.CharField(max_length=200)),
                ("about", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("business_email", models.EmailField(blank=True, max_length=254)),
                ("logo_url", models.URLField(blank=True)),
                ("cover_photo_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("wizard_step", models.PositiveIntegerField(default=0)),
                ("wizard_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym Profile",
                "verbose_name_plural": "Gym Profiles",
            },
        ),
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trainer_type",
                    models.CharField(
                        choices=[
                            ("independent", "Independent"),
                            ("gym_trainer", "Gym Trainer"),
                        ],
                        db_index=True,
                        default="independent",
                        max_length=20,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="full_name", unique=True
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("pricing_range", models.CharField(blank=True, max_length=200)),
                ("profile_photo_url", models.URLField(blank=True)),
                ("cover_photo_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "avg_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("wizard_step", models.PositiveIntegerField(default=0)),
                ("wizard_completed", models.BooleanField(default=False)),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gym_trainers",
                        to="profiles.gymprofile",
                    ),
                ),
                (
                    "specialisations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="trainers",
                        to="profiles.specialisation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trainer Profile",
                "verbose_name_plural": "Trainer Profiles",
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("issuing_body", models.CharField(blank=True, max_length=200)),
                ("year_obtained", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="profiles.trainerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
            },
        ),
        migrations.CreateModel(
            name="GymTrainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("trainer", "Trainer")],
                        default="trainer",
                        max_length=20,
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_trainer_memberships",
                        to="profiles.gymprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gym_memberships",
                        to="profiles.trainerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gym Trainer",
                "verbose_name_plural": "Gym Trainers",
                "unique_together": {("gym", "trainer")},
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("virtual", "Virtual"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=10,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("virtual_platform", models.CharField(blank=True, max_length=100)),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Morning HIIT class, Evening yoga",
                        max_length=200,
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="profiles.gymprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="profiles.trainerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("trainer__isnull", False)),
                        fields=("trainer", "day_of_week"),
                        name="unique_trainer_day",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("gym__isnull", False)),
                        fields=("gym", "day_of_week"),
                        name="unique_gym_day",
                    ),
                ],
            },
        ),
    ]
