# Generated by Django 5.2 — data migration for predefined specialisations

from django.db import migrations

SPECIALISATIONS = [
    "Weight Loss",
    "Muscle Building",
    "HIIT",
    "Strength Training",
    "Yoga",
    "Pilates",
    "Nutrition Coaching",
    "Rehabilitation",
    "Boxing",
    "Dance Fitness",
    "Cardio",
    "CrossFit",
    "Calisthenics",
    "Powerlifting",
    "Bodybuilding",
    "Mobility & Flexibility",
    "Pre/Postnatal Fitness",
    "Senior Fitness",
    "Sports Performance",
    "Functional Training",
]


def seed_specialisations(apps, schema_editor):
    Specialisation = apps.get_model("profiles", "Specialisation")
    for name in SPECIALISATIONS:
        Specialisation.objects.get_or_create(
            name=name, defaults={"is_predefined": True}
        )


def unseed_specialisations(apps, schema_editor):
    Specialisation = apps.get_model("profiles", "Specialisation")
    Specialisation.objects.filter(name__in=SPECIALISATIONS, is_predefined=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_specialisations, unseed_specialisations),
    ]
