# Generated by Django 5.2.12 on 2026-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="tracker_addon_active",
            field=models.BooleanField(default=False),
        ),
    ]
