# Generated by Django 5.2.12 on 2026-04-30 07:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_clientprofile_tracker_addon_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gymprofile",
            old_name="admin_full_name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="clientprofile",
            name="display_name",
        ),
        migrations.RemoveField(
            model_name="gymprofile",
            name="gym_name",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="gymprofile",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="full_name", unique=True
            ),
        ),
    ]
