# Generated by Django 5.2.12 on 2026-05-14 09:32

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_rename_admin_full_name_gymprofile_full_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("is_predefined", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="gymprofile",
            name="wizard_completed",
        ),
        migrations.RemoveField(
            model_name="gymprofile",
            name="wizard_step",
        ),
        migrations.RemoveField(
            model_name="trainerprofile",
            name="wizard_completed",
        ),
        migrations.RemoveField(
            model_name="trainerprofile",
            name="wizard_step",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="specialisations",
            field=models.ManyToManyField(
                blank=True, related_name="clients", to="profiles.specialisation"
            ),
        ),
        migrations.AddField(
            model_name="gymprofile",
            name="offers_products",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainerprofile",
            name="offers_products",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="primary_goals",
            field=models.ManyToManyField(
                blank=True, related_name="clients", to="profiles.goal"
            ),
        ),
    ]
