# Generated by Django 5.2.12 on 2026-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0008_seed_goals"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymprofile",
            name="specialisations",
            field=models.ManyToManyField(
                blank=True, related_name="gyms", to="profiles.specialisation"
            ),
        ),
    ]
