# Generated by Django 5.2.12 on 2026-05-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_display_name_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_step",
            field=models.IntegerField(default=0),
        ),
    ]
