# Generated by Django 5.2.12 on 2026-04-26 07:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0005_clientprofile_tracker_addon_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyNutritionLog",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("calorie_goal", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "protein_goal_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs_goal_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat_goal_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_logs",
                        to="profiles.clientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "unique_together": {("client", "date")},
            },
        ),
        migrations.CreateModel(
            name="MealEntry",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snacks", "Snacks"),
                        ],
                        max_length=20,
                    ),
                ),
                ("food_name", models.CharField(max_length=200)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Grams"),
                            ("ml", "Millilitres"),
                            ("serving", "Serving"),
                        ],
                        default="serving",
                        max_length=10,
                    ),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "nutrition_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="trackers.dailynutritionlog",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to="profiles.clientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseEntry",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sets", models.PositiveIntegerField(default=1)),
                ("reps", models.PositiveIntegerField(default=1)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="trackers.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
