# Generated by Django 5.2.12 on 2026-03-19 23:19

from django.db import migrations


def seed_plans(apps, schema_editor):
    PlanConfig = apps.get_model("subscriptions", "PlanConfig")

    plans = [
        {
            "plan": "basic",
            "display_name": "Basic",
            "price_ngn": 5000,
            "price_usd": 5,
            "trial_days": 14,
            "features": [
                "Up to 10 clients",
                "Basic workout builder",
                "Client progress tracking",
                "Email support",
            ],
            "is_active": True,
        },
        {
            "plan": "pro",
            "display_name": "Pro",
            "price_ngn": 12000,
            "price_usd": 12,
            "trial_days": 14,
            "features": [
                "Unlimited clients",
                "Advanced workout builder",
                "Nutrition tracking",
                "Analytics dashboard",
                "Priority support",
                "Marketplace listing",
            ],
            "is_active": True,
        },
    ]

    for plan_data in plans:
        PlanConfig.objects.get_or_create(plan=plan_data["plan"], defaults=plan_data)


def unseed_plans(apps, schema_editor):
    PlanConfig = apps.get_model("subscriptions", "PlanConfig")
    PlanConfig.objects.filter(plan__in=["basic", "pro"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_code=unseed_plans),
    ]
