# Generated by Django 5.2.12 on 2026-03-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0003_planconfig_deleted_at_subscription_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_payment_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="next_payment_retry_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="payment_retry_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
