# Generated by Django 5.2.12 on 2026-03-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_payment_retry_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="next_payment_retry_at",
        ),
        migrations.AddField(
            model_name="planconfig",
            name="paystack_plan_code",
            field=models.CharField(
                blank=True,
                help_text="Create a plan in Paystack Dashboard → Products → Plans. Monthly amount should match price_ngn. Copy the plan code (PLN_xxxxxxxx) here.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="planconfig",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Create a price in Stripe Dashboard → Products → Prices. Copy the price ID (price_xxxxxxxx) here.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_customer_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack customer code, e.g. CUS_xxx",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_email_token",
            field=models.CharField(
                blank=True,
                help_text="Used to manage subscription on Paystack",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="paystack_subscription_code",
            field=models.CharField(
                blank=True,
                help_text="Paystack subscription code, e.g. SUB_xxx",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="last_payment_retry_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last payment failure notification.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="payment_retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of payment failures received from Paystack/Stripe webhooks.",
            ),
        ),
    ]
