# Generated by Django 5.2.12 on 2026-03-25 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0003_service_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("uses_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_links",
                        to="profiles.gymprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invite_links",
                        to="profiles.trainerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("lapsed", "Lapsed"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("renewal_date", models.DateField(blank=True, null=True)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_currency", models.CharField(default="NGN", max_length=3)),
                ("payment_notes", models.TextField(blank=True)),
                ("last_reminder_at", models.DateTimeField(blank=True, null=True)),
                ("sessions_count", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="profiles.clientprofile",
                    ),
                ),
                (
                    "gym",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_memberships",
                        to="profiles.gymprofile",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_memberships",
                        to="profiles.trainerprofile",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("trainer__isnull", False)),
                        fields=("client", "trainer"),
                        name="unique_client_trainer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("gym__isnull", False)),
                        fields=("client", "gym"),
                        name="unique_client_gym",
                    ),
                ],
            },
        ),
    ]
