# Generated by Django 5.2.12 on 2026-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientmembership",
            name="unique_client_trainer",
        ),
        migrations.RemoveConstraint(
            model_name="clientmembership",
            name="unique_client_gym",
        ),
        migrations.AlterField(
            model_name="clientmembership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("lapsed", "Lapsed"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
    ]
