# Generated by Django 5.2.12 on 2026-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("chat_message", "Chat Message"),
                    ("direct_message", "Direct Message"),
                    ("client_joined", "Client Joined"),
                    ("payment_reminder", "Payment Reminder"),
                    ("subscription_locked", "Subscription Locked"),
                    ("new_review", "New Review"),
                    ("marketplace_enquiry", "Marketplace Enquiry"),
                    ("enquiry_response", "Enquiry Response"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
